<h3>REDIRECT KICKS IN</h3>
<h4>This happens when (foremost) the locale namespace is invalid, i.e uk, i.e, nl then its hits here</h4>

<table border="1" cellpadding="10">
    <tr>
        <th>Referrer</th>
        <th>Request</th>
        <th>Redirect</th>
    </tr>
    <tr>
        <td>davidlloyd.co.uk</td>
        <td>/metro</td>
        <td>/uk/october/metro</td>
    </tr>
    <tr>
        <td>davidlloyd.ie</td>
        <td>/metro</td>
        <td>/ie/october/metro</td>
    </tr>
    <tr>
        <td>davidlloyd.co.uk</td>
        <td>/3</td>
        <td>/uk/november/3</td>
    </tr>
</table>

<h1>404</h1>
<h2>The router could not find a match for the above table</h2>
<h3>So the redirect never happend, which caused this page to display</h3>
<h4>Which is also the 404 page</h4>

<a href="/uk/oct2013/metro/">example</a>