
<?php
function arrayToString(array $array, $level = 0){
    $indent = str_repeat("\t", $level);
    $str = "";
    if (!empty($array)){
        foreach($array AS $key=>$val){   
            if (is_array($val)){
                $str.= "{$indent}[$key] => ".arrayToString($val, ++$level);
            } elseif (is_object($val)){
                
                if (method_exists($val, 'toArray')){                    
                    $str.= "{$indent}[$key] => ".arrayToString($val->toArray(), ++$level);
                } else {
                    $str.= "{$indent}[$key] => (obj)";
                }
                
            } else {
                $str.= "\r\n{$indent}[$key] => <strong>$val</strong>";
            }
        }
    }
    return "$str";
}
?>

<div class="row">

    <h1 class="span12"><?php echo $this->api->description; ?></h1>

    <table class="table table-condensed table-hover table-bordered span12">

        <thead>
            <tr>                    
                <th>Service</th>                
                <th class="span2">Description</th>
                <th class="span1">Status</th>
                <th colspan="4" style="text-align:center;">Parameters</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach($this->api AS $componentKey=>$component) : ?>

                <tr>     
                    
                    <!-- SERVICE -->
                    <td>
                        <a href="<?php echo $this->url($component->route->name, $component->route->arguments); ?>" target="_BLANK">
                            <?php echo $this->url($component->route->name, $component->route->arguments); ?>
                        </a>                        
                    </td>
                    
                    <!-- DESC -->
                    <td>
                        <?php echo ucfirst($component->description); ?>
                        <?php if ($component->alert) : ?>
                            <br />
                            <div class="alert alert-danger">
                                <?php echo $component->alert; ?>
                            </div>
                        <?php endif; ?>
                    </td>
                    
                    <!-- STATUS -->
                    <td>
                        
                        <?php     
                        switch(strtolower($component->status)){

                            case 'depricated': ?>                    
                                <span class="label label-warning">
                                    <i class="icon-exclamation-sign icon-white"></i>&nbsp;Depricated
                                </span>          
                            <?php
                            break;

                            case 'removed': ?>
                                <span class="label label-important">
                                    <i class="icon-exclamation-sign icon-white"></i>&nbsp;Removed
                                </span>          
                            <?php
                            break;

                            case 'unfinished': ?>
                                <span class="label label-important">
                                    <i class="icon-exclamation-sign icon-white"></i>&nbsp;Unfinished
                                </span>          
                            <?php
                            break;

                            default: ?>                                
                                <!--i class="icon-ok-sign"></i-->                                
                            <?php
                            break;
                        }
                        ?>
 
                    </td>    
   

                    
                    <!-- REQUIRES -->
                    <td>                        
                        <?php

                            $requiredArguments = array_filter($component->arguments,create_function('$a', 'return $a->required ? true : false;'));                              
                            if (count($requiredArguments)>0) : ?>
                                <table class="table table-bordered">
                                    <tr>
                                        <th colspan="2">Requires</th>
                                    </tr>
                                    <?php foreach($requiredArguments AS $argument) : ?>
                                        <tr>
                                            <td><?php echo $argument->name; ?></td>
                                            <td><?php echo $argument->datatype; ?></td>                                      
                                        </tr>
                                    <?php endforeach; ?>
                                </table>
                        <?php endif; ?>                         
                    </td>
                    
                    <!-- ACCEPTS -->
                    <td>
                        <?php
                        
                            $notRequiredArguments = array_filter($component->arguments,create_function('$a', 'return !$a->required ? true : false;'));                            
                            if (count($notRequiredArguments)>0) : ?>
                                <table class="table table-bordered">
                                    <tr>
                                        <th colspan="2">Accepts</th>
                                    </tr>
                                    <?php foreach($notRequiredArguments AS $argument) : ?>
                                        <tr>
                                            <td><?php echo $argument->name; ?></td>
                                            <td><?php echo $argument->datatype; ?></td>                                      
                                        </tr>
                                    <?php endforeach; ?>
                                </table>
                        <?php endif; ?> 
                    </td>
                    
                    
                    <!-- RETURNS -->
                    <td>
                        <?php                            
                            if (count($component->returns)>0) : ?>
                                <table class="table table-bordered">
                                    <tr>
                                        <th colspan="2">Returns</th>
                                    </tr>
                                    <?php foreach($component->returns AS $argKey=>$argument) : ?>
                                        <tr>
                                            <td><?php echo $argument->name; ?></td>
                                            <td>
                                                
                                                <?php
                                                switch($argument->datatype){
                                                    
                                                    case 'array':
                                                        
                                                        if (!empty($argument->details)){
                                                            echo "<a href='#' onclick='$(\"#arg{$argKey}{$componentKey}\").toggle(\"slow\"); return false;'>".ucfirst($argument->datatype)."</a>";
                                                            echo "<pre id='arg{$argKey}{$componentKey}' style=\"display: none;\">".arrayToString($argument->details)."</pre>";
                                                            //echo "<pre id='arg{$argKey}{$componentKey}'>".arrayToString($argument->details)."</pre>";
                                                            break;
                                                        }
                                                        
                                                    default:
                                                        echo ucfirst($argument->datatype);

                                                }

                                                ?>
                                                
                                            </td>                                      
                                        </tr>
                                    <?php endforeach; ?>
                                </table>
                        <?php endif; ?>                        
                    </td>                       
                </tr>
            <?php endforeach; ?> 

        </tbody>


    </table>

</div>

